apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-service
spec:
  ports:
  - port: 80
    targetPort: 8000
  type: NodePort
  selector:
    app: example-pod
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: example-replica
  labels:
    app: example-replica
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-pod
    spec:
      containers:
      - name: example-container
        image: zlabjp/docker-example:release-0.1.0
        ports:
        - containerPort: 8000